language: php

env:
  global:
    - SETUP=stable

php:
  - 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql
  - redis-server

before_script:
  - printf "\n" | pecl install -f redis-4.3.0
  - mysql -e 'create database if not exists meedutest;'
  - cp .env.testing .env
  - php artisan key:generate

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 9e51b0b6-e5bf-457a-a116-8b5fdc95da80